### PR TITLE
added adopt-liveview-notes.md #228

### PR DESCRIPTION
**Pull request by MikeRund**
Included notes from the Adopt LiveView  beginner track course covering:

+ Fundamentals
+ HEEx
+ Events
+ Navigation
+ Components

### CODE REVIEW

**Comment by nelsonic** [comment]
I haven't forgotten this PR. Just a little overwhelmed with everything right now so a `1.4kloc` PR feels daunting ... 🙃 😜 
As soon as it rains again I will sit down and review. 🧑‍💻 
But for now the sun is shining ☀️ so I _must_ be working outside. 👷 🚧 
Cause `#WinterIsComing` and I have to do as _much_ building work as possible before it rains! ⏳ 🌧️ 😬

**Comment by MikeRund** [comment]
Don't worry I expected as much! Far more pressing things to do! 🏡☀️

**Comment by nelsonic** [comment]
image

on it now. 🧑‍💻 🏥 ⏳

**Comment by MikeRund** [comment]
A very impressive use of time 😬

**Review by nelsonic — APPROVED** [review]
Great notes @MikeRund 👌

**Comment by MikeRund** [comment]
Awesome! Glad to hear

**Pull request merged**
