### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EmondW**
Removed incorrect/old syntax from template

### CODE REVIEW

**Review by nelsonic — COMMENTED** [review]
I thought this “.” Syntax was the _new_ way of doing it… 🤷‍♂️💭 need to re-read the docs…

**Comment by EmondW** [comment]
I am new to phoenix liveview and while following the tutorial and writing the code, with the dots, I got this compilation error:

```
== Compilation error in file lib/live_view_counter_web/live/counter.ex ==
** (CompileError) lib/live_view_counter_web/live/counter.ex:17: undefined function button/1 (expected LiveViewCounterWeb.Counter to define such a function or for it to be imported, but none are available)
```

Looking at the documentation did not help a lot, unfortunately (which could be my fault)

I also noticed that the number of tests is different (just 3 instead of 5)

Perhaps it is a version difference. The versions I used:

```
~\Source\Elixir\Tutorials\live_view_counter>  elixir -v
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

~\Source\Elixir\Tutorials\live_view_counter>  mix phx.new -v
Phoenix installer v1.6.15
```

**Review by nelsonic — DISMISSED** [review]
Thanks for confirming @EmondW please update to [`Phoenix @ v1.7.0-rc.2`](https://github.com/phoenixframework/phoenix/releases/tag/v1.7.0-rc.2)

```sh
mix archive.install hex phx_new 1.7.0-rc.2
```

And try again. This tutorial uses the _latest_ "Release Candidate" version. 💭

**Comment by SimonLab** [comment]
The `<.button>` is a [Phoenix Live Component](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html)

So the code called by this component is:
https://github.com/dwyl/phoenix-liveview-counter-tutorial/blob/9fb43b748c0cbb67beb63db3656de937ee2bead6/lib/live_view_counter_web/components/core_components.ex#L98-L126

I can try to run the project again on my machine to make sure

**Comment by EmondW** [comment]
I have a suspicion now: while following the instructions of the tutorial, I used 

mix archive.install hex phx_new

to install phoenix liveview. This installed version 

> Thanks for confirming @EmondW please update to [`Phoenix @ v1.7.0-rc.2`](https://github.com/phoenixframework/phoenix/releases/tag/v1.7.0-rc.2)
> 
> ```shell
> mix archive.install hex phx_new 1.7.0-rc.2
> ```
> 
> And try again. This tutorial uses the _latest_ "Release Candidate" version. 💭

This should be in the prerequisits of the tutorial! The instructions install the latest stable (non rc) version.

**Pull request merged**
