### PR TITLE
Phoenix 1.7

### PR DESCRIPTION
**Pull request by chargio**
A first version, fully working, using Phoenix 1.7-rc.0.
Trying to understand how to record the gifs and upload images to finish it when 1.7 is out.

Please don't merge it yet (although it is working).

### CODE REVIEW

**Comment by nelsonic** [comment]
@chargio thanks for making time to create this PR! 🎉 
The CI/Build fails because the version of `Elixir` in the `ci.yml` file is set to `v1.12.3`:

https://github.com/dwyl/phoenix-liveview-counter-tutorial/blob/63366b18323526519e59aa8296282edbb9b99677/.github/workflows/ci.yml#L19-L20

See: https://github.com/dwyl/phoenix-liveview-counter-tutorial/actions/runs/3530284308/jobs/5922111604#step:6:151
image

So we need to borrow the following lines directly from the Phoenix `ci.yml` to get `elixir: 1.14.0`:
https://github.com/phoenixframework/phoenix/blob/3cf1f1065ce11a906bd04b7841814cdced3f0df2/.github/workflows/ci.yml#L19-L20

image

Once that is updated the build should pass. 🤞 
Thanks! 🙏

**Comment by chargio** [comment]
Just to be clear. I can't make the changes in the ci environment myself

**Comment by chargio** [comment]
Discovered the error and fixed it. 1.7 has slighty different files for live tests. I've copied them from my own version of this to be sure I am not missing anything.

There is one error remaining: for some reason, in 1.7 the number of current users is one more than the actual number of users, looking at it

**Comment by chargio** [comment]
Ok. Now I found the error in the code.
You counted the number of users after subscribing. It seems like the subscribe in 1.7 changes the number of users without the need for the diff event

**Comment by nelsonic** [comment]
Hi @chargio this PR looks like it's ready. It hasn't been reviewed because still assigned to you. Please LMK if you're done. Thanks. 👍

**Review by nelsonic — APPROVED** [review]
Merging as CI is passing and this is a great update. 🎉 
Thanks again @chargio 🙌

**Comment by chargio** [comment]
Hey. I was waiting for the final release of 1.7 to ask for it to be merged, but happy to see that is done.

The only thing: I couldn't update the screenshots, so they are still from the old version, and my experience with CSS is limited, so it does not look as good as before

**Comment by nelsonic** [comment]
@chargio don't worry about any of that. 👌 
`CSS` Polish can always be applied by anyone else learning from the tutorial.  ✨ 
This is _especially_ easy now that `Tailwind CSS` is included with `Phoenix` 🦄 
Thanks again for your superb update. 🚀

**Pull request merged**
