### PR TITLE
Update to Bandit instead of Cowboy

### LINKED ISSUE #216: Why `present` increase when refresh the page?
I encounter a problem that the "connected clients" count increase each time I refresh the page. What's the reason of this issue and how could I fix it?

https://github.com/user-attachments/assets/926f29a6-c80c-442a-ba27-0a532c9697d8

### PR DESCRIPTION
**Pull request by ndrean**
I also added the missing "logo.svg" as the folder "priv/static/" was in ".gitignore". The error is therefor removed. #185

This should close #216

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@ndrean excellent update as always. ❤️ 🙏 
Could you please just update the version of `Elixir` in the  GitHub Actions CI so it doesn't fail? 
https://github.com/dwyl/phoenix-liveview-counter-tutorial/actions/runs/11164278975/job/31033222438
image

**Comment by nelsonic** [comment]
This line needs to be updated: 
https://github.com/dwyl/phoenix-liveview-counter-tutorial/blob/459ca55e1080c7c51701fd374ce9a9d8a85c66d5/.github/workflows/ci.yml#L19

**Comment by ndrean** [comment]
I will also close #214 by adding commented classes !!!???!!! Works...

**Comment by ndrean** [comment]
#213 should also be closed with this I believe.

**Comment by ndrean** [comment]
Also to update the resumé:

 ```
beginners tutorial building a real time counter in 

> Phoenix 1.7.7 + LiveView 0.19

 ⚡️ 
Phoenix 1.7.14 + LiveView 1.0

Learn the fundamentals from first principals so you can make something amazing!
```

**Review by nelsonic — APPROVED** [review]
Nice @ndrean ❤️

**Pull request merged**
